### ISSUE TITLE
Failed to import tailwindcss

### ISSUE THREAD

**Issue by sikeat7** [xmimiex/vue3-ssr-template#45]
Failed to import Tailwindcss got an error:
import '@app/assets/css/tailwind.css'
@tailwind base;
@tailwind components;
@tailwind utilities;

RangeError: Maximum call stack size exceeded
    at collectCssUrls (/Users/user/vue3-ssr-template/src/server/controllers/render-app-dev-server.ts:18:28)
    at collectCssUrls (/Users/user/Vue3/vue3-ssr-template/src/server/controllers/render-app-dev-server.ts:26:11)
    at collectCssUrls (/Users/user/Vue3/vue3-ssr-template/src/server/controllers/render-app-dev-server.ts:26:11)
    at collectCssUrls (/Users/user/Vue3/vue3-ssr-template/src/server/controllers/render-app-dev-server.ts:26:11)
    at collectCssUrls (/Users/user/Vue3/vue3-ssr-template/src/server/controllers/render-app-dev-server.ts:26:11)
    at collectCssUrls (/Users/user/Vue3/vue3-ssr-template/src/server/controllers/render-app-dev-server.ts:26:11)

**Comment by jcfauchet** [comment]
Should be fixed after https://github.com/xmimiex/vue3-ssr-template/pull/46 merge
